import { Inter } from "next/font/google";
import "./globals.css";
import AllProviders from "@/components/Providers/AllProviders";
import Navbar from "@/components/Layout/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="id">
      <body className={inter.className}>
        <AllProviders>
          <Navbar>
            {children}
          </Navbar>
        </AllProviders>
      </body>
    </html>
  );
}
